### ISSUE TITLE
Consistancy Issue

### ISSUE THREAD

**Issue by jinyz8888** [UBC-MDS/test-creation#119]
@SoloSynth1 @tonyshumlh @JohnShiuMK 
I run the program twice, and the result of the first run is:
![image](https://github.com/UBC-MDS/test-creation/assets/108684429/c6deee38-ce46-4b5a-9bd3-0733e84b6ba7)

and the result of the second run is:
![image](https://github.com/UBC-MDS/test-creation/assets/108684429/a030bf50-1dc9-4dc1-ae8a-e227f9101053)

The differences are in number of files checked, different checklist items and different scores. Please check it. Thanks.

**Comment by JohnShiuMK** [comment]
Hi @jinyz8888, this will be addressed by #101. I'm currently reviewing it.
Thanks

**Comment by JohnShiuMK** [comment]
> Hi @jinyz8888, this will be addressed by #101. I'm currently reviewing it. Thanks

Hi @jinyz8888, could you please git pull from main and try again?

**Comment by jinyz8888** [comment]
@tonyshumlh  and I tested it again, the n_files_tested is not changed anymore. Thus, this issue is closed.
