### ISSUE TITLE
Questions to be address

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/test-creation#12]
1. Expectation alignment
   - John: User story (instructor) --> 3 outcomes from our tool --> week 1, 2, 3 works
   - Tony: (if time allows) User story (student prospective)
   - Orix: in the worst case scenario, which part of our project should we focus on? / what are the priorities for our objectives?
   - Yingzi: what are the priorities for our objectives?
 2. Success metrics: how to evaluate our project quality?
 3. Resources
 5. It seems that what we're doing now is violating test driven development that you taught?

**Comment by jinyz8888** [comment]
@SoloSynth1 @JohnShiuMK @tonyshumlh Can I add an expectation alignment? 
Yingzi: what are the priorities for our objectives?

**Comment by JohnShiuMK** [comment]
Here are some bullet points we talked about with Tiffany and Simon this afternoon:

 - Meaning of test driven: function skeleton --> test --> function
 - What we should focus on could be based on our interest
 - Something to keep in mind:
   - Checklist is definitely something publishable. (e.g. we can say based on our observation of xxxx)
   - Out of the whole checklist, we may see that some of them are general and more straightforward. If so, e.g. pick one or two items from checklist (start with something fundamental), we should build from there first.
 - It would be great if we could also take into account Tiffany's checklist
 - Expectation on the deliverable: Workflow is the most important, even though they are just not working well pieces
 - To check budget of the ChatGPT cost, API
 - Success: Mutation testing (for each item of the checklist), maybe with the help of ChatGPT

**Comment by JohnShiuMK** [comment]
Done, thanks all
