### ISSUE TITLE
Code Analyzer Improvement

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/test-creation#132]
I have spotted that the `code_analyzer` might accidentally regard some model training functions as test functions.
e.g. `test_epoch` function in the `qlib` repo. This also increases the workload of the LLM
It would be great if the `code_analyzer` could be more strict, or it enables users to select/disselect the test files to be passed into LLM.

<img width="559" alt="Screenshot 2024-06-03 at 12 35 32 PM" src="https://github.com/UBC-MDS/test-creation/assets/38127942/18251197-9f36-49af-933d-8453d8f4b10c">

<img width="593" alt="Screenshot 2024-06-03 at 12 41 17 PM" src="https://github.com/UBC-MDS/test-creation/assets/38127942/6be399b5-aab6-4442-90b3-7d9896d41739">

**Comment by JohnShiuMK** [comment]
to be confirmed: the system seems to have problems on `nupic-legacy`

**Comment by JohnShiuMK** [comment]
John to determine whether the file path e.g. `....../tests/` can be a universal rule

**Comment by JohnShiuMK** [comment]
note: './openja/magenta/magenta/models/music_vae/data_test.py'. The system failed to run this file for unknown reason
![Uploading Screenshot 2024-06-05 at 1.36.16 PM.png…]()

**Comment by JohnShiuMK** [comment]
Note: './openja/magenta/magenta/models/music_vae/data_test.py'. The system failed to evaluate this file for unknown reason
<img width="1350" alt="Screenshot 2024-06-05 at 1 36 16 PM" src="https://github.com/UBC-MDS/test-creation/assets/26508851/7e238fe8-9dea-4d28-a439-f53dfdb12d79">

**Comment by SoloSynth1** [comment]
@tonyshumlh test files extracted from `microsoft/qlib` after logic refinement:
![image](https://github.com/UBC-MDS/test-creation/assets/17952490/1ac9b73e-7cf2-44e5-9049-b1a67dee3924)

**Comment by SoloSynth1** [comment]
> to be confirmed: the system seems to have problems on the repo `nupic-legacy`

Confirmed - This should be caused by the encoding of the file. Will push a fix on this.

**Comment by JohnShiuMK** [comment]
<img width="1440" alt="Screenshot 2024-06-07 at 11 21 09 AM" src="https://github.com/UBC-MDS/test-creation/assets/26508851/82ad3e98-dc28-4319-b879-0ca3b78026b6">

These warnings happen in `deepchem` and `apollo` fyi @SoloSynth1

**Comment by SoloSynth1** [comment]
> <img alt="Screenshot 2024-06-07 at 11 21 09 AM" width="1440" src="https://private-user-images.githubusercontent.com/26508851/337753186-82ad3e98-dc28-4319-b879-0ca3b78026b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3OTE3NzQsIm5iZiI6MTcxNzc5MTQ3NCwicGF0aCI6Ii8yNjUwODg1MS8zMzc3NTMxODYtODJhZDNlOTgtZGMyOC00MzE5LWI4NzktMGNhM2I3ODAyNmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDIwMTc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NmYwNTIwYTA2NDMxMWUxMWUwZmQxZTMyMWVkNDY3MzNkZDZmZmQwNzE5ZDFlMzYwMjVjZWFlNmQwNTRmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fxvAZt9rOSpRW9gcTQyq3SkUVORuzspNM3xZajyzNuM">
> These warnings happen in `deepchem` and `apollo` fyi @SoloSynth1

These are from `ast` and are expected. If `ast` raises error then `NaiveCodeAnalyzer` will take over, which is why the program kept running without halting
