### ISSUE TITLE
Question on Presentation Script

### ISSUE THREAD

**Issue by jinyz8888** [UBC-MDS/test-creation#15]
Firstly, @JohnShiuMK @SoloSynth1 and @tonyshumlh, thanks for the idea of role play part, and thanks @tonyshumlh for the work on the script.  I just have a question on it: one of objectives of MDS program is to teach students how to write test cases and ask students to practice on it, but in our presentation script, it seems we tell students to use our product instead of themselves to write test cases, is it okay or suitable? Can we use another user case in the role play script?

**Comment by SimonGoring** [comment]
My sense is that you're good here. I think our general advice for anything coming from ChatGPT is not to trust it implicitly. You still need to check it out, see if it's doing what you want it to do and modify as needed.

If you present it in that sense I think you're good. Maybe the output could come with that disclaimer embedded in it as a comment, and the student in your role play could acknowledge that too.

You are not entirely doing the work for them, you're giving them the tools to do that work more effectively.

**Comment by jinyz8888** [comment]
@SimonGoring Thanks for your comments. In the presentation script, we used 522 program as a user case to tell students to use our product for their projects in MDS program. My question is if this scenario is appropriate in our presentation, some other scenario maybe more good used in our role play script.

**Comment by SimonGoring** [comment]
@jinyz8888 I think it's fine, just with the caveat that they mention that it's useful and they'll clean up the scripts.

**Comment by jinyz8888** [comment]
@SimonGoring Thanks for answering my questions.
