### ISSUE TITLE
Finish the draft of the proposal

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/test-creation#18]
- [x] Review before submission (John)
- [x] Review before submission (Tony)
- [x] Review before submission (Orix)
- [x] Review before submission (Yingzi)
- [x] #42
- [x] Add references

**Comment by JohnShiuMK** [comment]
sub-task of #3

**Comment by jinyz8888** [comment]
@tonyshumlh Thanks for the proposal, it is concise and well-organized. It is very hard to give some suggestions. Is it okay to add some sentences in the "3.3.3 Iterative Development Approach" part to make it more clear?

3.3.3 Iterative Development Approach
As we leverage data from selected GitHub repositories and references research on testing strategies, it's important to acknowledge that this may not include all ML systems or testing methodologies. To address these considerations, we adopt an iterative development approach by setting up an open and scalable framework for this project. Our application could then undergo continuous updates based on users' feedback and contributors' insights.

> In this approach, we begin by setting up a foundational framework that incorporates initial checklists, LLM prompts, and test specifications. This framework serves as our starting point, allowing us to gather preliminary feedback and performance metrics. After the initial deployment, we actively seek feedback from early adopters and domain experts. We utilize this feedback to identify areas where our test checklists and LLM prompts can be expanded or refined to better meet the needs of diverse ML projects.

We encourage users to interpret the artifacts generated by the application with a grain of salt and recognize the evolving nature of ML system testing practices.

**Comment by SoloSynth1** [comment]
@jinyz8888 I think in terms of the test specifications, they are generated so there would be no incorporations with the checklist and the LLM prompts. In other words, the checklist and the LLM prompt are the input, while the test specifications are the output.

Also, we would be seeking feedbacks from our partner and past researches, instead of early adopters and domain experts.

**Comment by jinyz8888** [comment]
@SoloSynth1  I think the lifecycle of our product and the iteration process are not just these two months,  the output of this project is the initial product, after that, maybe next year, there’re some feedbacks from other students or domain experts (if it is used in commercial way).

**Comment by SoloSynth1** [comment]
AFAIK the iterative development approach applies to the developments that will happen within week 3-6, which we have laid out during the presentation of our proposal.

In addition, the proposal ["is intended to set goals and directions for your capstone project"](https://pages.github.ubc.ca/MDS-2023-24/DSCI_591_capstone-proj_students/deliverables/1-proposal-presentation-and-report.html#deliverable-description). I don't think there is a need to mention any legacy plan beyond our 2-month timeframe.

**Comment by SoloSynth1** [comment]
Closing this as we have moved past the draft version.
