### ISSUE TITLE
Teamwork Contract

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/test-creation#2]
I have some templates from my historical project courses, see which one you guys prefer:

https://docs.google.com/document/d/1TWnsfsitVGPyGRFRPcKO5ongzslMjnIzTLowtG8b6Sc/edit?usp=drive_link
https://docs.google.com/document/d/1zUsbRw4TQxPyizz6ts1GZdFdakftn0rWQtwAR286zGc/edit?usp=drive_link
https://docs.google.com/document/d/1Cy46JE9LAgkcFc-sSYCsFzd3i30vBy8F3BOMlLOE66g/edit?usp=drive_link

**Comment by JohnShiuMK** [comment]
1. Establish modes of communication amongst your teammates. Remember, capstone is fluid; these modes can change throughout the project if appropriate.
  - Unless you have reason to suggest otherwise, three modes are useful:
    - A students-only slack channel for your group members.
    - GitHub Issues, on your main project repo where you will be developing your data product.
    - In-person meetings and/or remote meetings.
  - Distinguish what these different modes will be used for. Use GH Issues for self-contained topics that have some permanence so them, as they are possibly useful to refer to in the future; use Slack for ephemeral, conversational messages.

2. Establish a task management system. Where will you store store and manage all of your to-do’s. GH Projects and Issues? Asana? Todoist? Nozbe? etc.

3. Discuss the a group-specific meeting schedule and expectations on availability. For example, should group members be available between 10am - 4pm every day? Will the group meet everyday or just on Mondays and Fridays, etc.

4. Discuss expectations on communicaton and contributions. Will different members manage different aspects of the group or will everyone contribute equally. If a group member cannot complete an assigned task, how and when should they let the group know? etc.

**Comment by SoloSynth1** [comment]
Mine's for  DSCI-524:
https://docs.google.com/document/d/1IdZ3jpbT72svenogc8kt3ypc1ImT0K63/edit

**Comment by JohnShiuMK** [comment]
<img width="631" alt="Screenshot 2024-04-29 at 10 01 08 AM" src="https://github.com/UBC-MDS/test-creation/assets/26508851/c0485848-076d-425f-8142-9f342d63ca65">

**Comment by JohnShiuMK** [comment]
https://docs.google.com/document/d/1jiwNwY_9wk4WI2-NtZylfXnULFJAFDqhx6DYvKw0VTo/edit

**Comment by SoloSynth1** [comment]
https://docs.google.com/document/d/1gb4uv_NgPyyvXsheBwlKHrbvHPvR6Zmc86pgL-XPmtA/edit

**Comment by tonyshumlh** [comment]
finished
