### ISSUE TITLE
User story for MVP Repo Analyzer

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/test-creation#24]
As an aspiring junior data scientist, I want to know the degree of completion of the tests in my ML project. I want to have quantified score to evaluate how complete the test suite is. To do this, I expect this can be done with using this tool in the following workflow:

1. Open command line interface
2. Run the program with the repo link supplied
3. The program will return a overall score to indicate how complete the tests are
4. (Optional) The program will return explanations on the given score / list of missing test cases

Explanation of why the system comes up with this score is good-to-have for this week, but not a must.

Items to do:
- [x] #30
- [x] #28
- [x] #35
- [x] #39
- [ ] Create a container image of the tool for code portability

**Comment by JohnShiuMK** [comment]
I think this can be closed for now. The container image can be postponed to a later stage, what do you think, @SoloSynth1?

**Comment by SoloSynth1** [comment]
> I think this can be closed for now. The container image can be postponed to a later stage, what do you think, @SoloSynth1?

Yeah sure, I'm gonna move the containerization item into the backlog to be considered later on.

Closing this issue.
