### ISSUE TITLE
Proposal and Presentation

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/test-creation#3]
- [x] #18 
- [ ] #19 
- [x] Initial Presentation

Proposal Requirement Summary

1. Executive Summary:
- Brief overview of the project proposal.
- Highlights of the problem statement, objectives, and proposed data product.
- Key points regarding the data science techniques to be used and the expected outcomes.
2. Introduction:
- Broad introduction to the problem statement or question being addressed.
- Importance and relevance of the problem statement.
- Refinement of the problem into specific, actionable objectives.
- Description of the final data product to be delivered to the partner.
- Example components of the data product (e.g., Shiny or Dash app, Python or R package, data pipeline, documentation).
3. Data Science Techniques:
- Explanation of how data science techniques will be utilized in the project.
- Assessment of data appropriateness for the proposed techniques.
- Discussion of potential difficulties with the data.
- Description of the data including variables/features and observational units.
- Examples or snippets of the data (table or visualization).
- Implementation of simple data science techniques initially for baseline comparison and potential problem resolution.
- Clear articulation of success criteria for the project, including evaluation metrics, expectations from the partner, and stakeholder impact.
4. Timeline:
- Rough timeline of the project.
- Milestones to be achieved at different stages of the project.
5. Proposal Report:
- Written report containing a maximum of 1200 words (excluding appendices, figure captions, and table captions).
- Audience includes capstone partner, project mentor, and fellow group members.
- Excellent writing quality, including proper sentence structure, grammar, and citations.
- Clear communication in own words with consideration for accessibility to non-technical audiences.
- Concise content mindful of the capstone partner's time.
- Graded based on understanding and refinement of capstone partner's needs, relevance of scientific objectives, usefulness of proposed products, thoughtfulness of data science approach, incorporation of feedback, and use of reproducible tools for report creation (e.g., Jupyter, RMarkdown, LaTeX).

**Comment by tonyshumlh** [comment]
Presentation Requirement Summary 
1. Introduction:

- Briefly introduce team members.
- Provide an overview of the partner organization's activities and their importance.
- Describe the current issue or problem faced by the partner organization.
- Explain how the proposed capstone products will add value to the organization by addressing the problem.
- Clearly state the success criteria for the capstone products.
2. Main Presentation Content:
- Use slides to effectively convey the message of the proposal.
- Each slide should focus on one purpose and include a clear take-home message.
- Limit the amount of text on slides and avoid word-heavy charts.
- Include visual elements such as diagrams and charts to aid understanding.
- Ensure slides are visually appealing and easy to follow.
- Use animations to focus audience attention on specific concepts.
- Use effective color schemes with good contrast and large enough font sizes.
- Choose inclusive language and limit the use of jargon.
- Include slide numbers for easy reference during Q&A.
3. Presentation Delivery:
- Speak clearly and audibly, maintaining an appropriate speaking volume.
- Engage the audience with body language and eye contact.
- Each team member should spend an equal amount of time presenting.
- During the Q&A session, answer questions directly and check with teammates if unsure.
- Be active during the presentation and follow-up discussion.
- Ensure equal participation among team members in answering questions.
- Avoid deflection and address questions directly.
- If unsure of an answer, defer to teammates rather than veering off-topic.
4. Conclusion:
- Summarize key points of the presentation.
- Thank the audience for their attention and open the floor for questions.

**Comment by tonyshumlh** [comment]
Proposal : https://github.com/UBC-MDS/test-creation/blob/proposal_doc/report/capstone_proposal.md

**Comment by tonyshumlh** [comment]
Presentation
Style: Professional
Content:
1. Mission & Values
2. Product Introduction
- Target Audience
- 1 graph to describe our product
3. Role Play
- 
4. Operation Timeline
-  
Flow:

**Comment by SoloSynth1** [comment]
Simon's feedback:
- user persona (student): find out about the checklist
- present a tool box to find out how well he/she performs
- keep narrative - stay at the big picture
