### ISSUE TITLE
Expanding checklist items

### ISSUE THREAD

**Issue by jinyz8888** [UBC-MDS/test-creation#63]
I've added some new items into the checklist, please view them at 
https://docs.google.com/spreadsheets/d/1cgMO67vwJx1TYQAT1bEvKxfEwPnelYhLBT_k8i3SEJA/edit#gid=1269311861
Please add comments or have a quick meeting to go through those items. If no questions on them, I'll add them into the system.

**Comment by jinyz8888** [comment]
@ttimbers I added four new items into the checklist and discussed it with @JohnShiuMK  this noon, please review it at <https://docs.google.com/spreadsheets/d/1cgMO67vwJx1TYQAT1bEvKxfEwPnelYhLBT_k8i3SEJA/edit#gid=1269311861>. Thanks.

**Comment by JohnShiuMK** [comment]
will move to future direction.
close it for now, good job!
