### ISSUE TITLE
Research questions with the colnames in spreadsheet about 377 github repos

### ISSUE THREAD

**Issue by jinyz8888** [UBC-MDS/test-creation#7]
Hello team,

Based on our discussion, here are the research questions for each column name in <https://docs.google.com/spreadsheets/d/e/2PACX-1vQ7gkxqJpzsa4T2ZuZg-VfAvD9U4r-XbpmwdlkK3k_RZ5Jc8bhgLK6I6xHj_KSTHTZaoJg-SqcE2yPj/pubhtml>

Colnames: Research questions
Referencing or not: whether or not links from GitHub README.md to academic papers
RQ1 Open Access: Whether or not  the academic papers referenced in GitHub README.mds are publicly available 
RQ2 Diversity of GitHub Repository: What kind of GitHub repository references an academic paper
RQ2 Affiliation: What is the affiliation of the owners of GitHub repositories that reference academic papers
RQ2 Paper References back to the Repository: Is there a [direct relationship](https://www.sciencedirect.com/topics/computer-science/direct-relationship) between the GitHub repository’s contributors and its referenced academic paper?
RQ3 README evolution: How do academic papers referenced in GitHub README.mds link back to the GitHub repository?
RQ3 Paper evolution: Do academic papers get updated after being referenced in GitHub README.mds?

Hope it is helpful

**Comment by SoloSynth1** [comment]
@jinyz8888 Would you mind to attach the links to the definitions?

**Comment by SoloSynth1** [comment]
[GitHub Repositories with Links to Academic Papers:
Public Access, Traceability, and Evolution](https://arxiv.org/pdf/2004.00199) (linking 377 GitHub repositories to academic papers)
