### ISSUE TITLE
Add metric (e.g. from regression model) to quantify the improvement of consistency

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/test-creation#76]
We can carry out F-test to test the equality of 2 variance (measurement for consistency)
We have 2 samples (1. before prompt/checklist/code change, 2. after prompt/checklist/code change)
Null Hypothesis: Sigma_1^2 = Sigma_2^2
Alternative Hypothesis: Sigma_1^2 > Sigma_2^2 (we want to prove if new change is more consistent than the original setting)
https://www.itl.nist.gov/div898/handbook/eda/section3/eda359.htm

**Comment by JohnShiuMK** [comment]
https://www.statisticshowto.com/probability-and-statistics/hypothesis-testing/f-test/#:~:text=F%20Test%20to%20Compare%20Two%20Variances,-A%20Statistical%20F&text=If%20the%20variances%20are%20equal,when%20running%20an%20F%20Test.

**Comment by JohnShiuMK** [comment]
According to #72 and #99 
I will update the consistency F-test from one-tail to two-tail (keep it in jupyter notebook)
  - (optional) to look at stat package if have time
