### ISSUE TITLE
Export report into HTML format

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/test-creation#82]

**Comment by jinyz8888** [comment]
The summary mentioned 

ID | Title | is_Satisfied | n_files_tested
-- | -- | -- | --
2.1 | Ensure Data File Loads as Expected | 1 | 7

![Screenshot 2024-05-22 at 3 39 47 PM](https://github.com/UBC-MDS/test-creation/assets/108684429/d6a4c8fe-2f45-49fa-9655-2587ef68b4fe)

but the observation shows some test files are not applicable, why does it give 1 for is_Satisfied?

2.1 Ensure Data File Loads as Expected
Requirement: Ensure that data-loading functions correctly load files when they exist and match the expected format, handle non-existent files appropriately, and return the expected results.

Observations:

(test_fast_functions.py) Not Applicable
nan
(test_datasets.py) The test functions validate the loading of data files from the ‘movielens’ and ‘stackexchange’ datasets, checking the shapes and types of the loaded data.
(test_cross_validation.py) The provided test functions do not directly test data file loading as they use the ‘fetch_movielens’ function which internally handles data loading.
(test_evaluation.py) The provided test functions do not involve loading data files; instead, they generate synthetic data for testing the model evaluation functions.
(test_data.py) The test functions do not involve data file loading; instead, they focus on dataset fitting, interactions, and features building.
nan

**Comment by JohnShiuMK** [comment]
> The test functions validate the loading of data files from the ‘movielens’ and ‘stackexchange’ datasets, checking the shapes and types of the loaded data.

@jinyz8888 thanks for checking. It's because the test_datasets.py satisfies, and the repository satisfies the item too.
