### ISSUE TITLE
Tidy up the repo folder structure

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/test-creation#86]
Simon:

By the end of the week, along with all your other work, I'd like to see:
 - [ ] #98
 - [x] Make sure everyone's branches are pushed and pulled into main or dev so that they are accessible to the team, and helpful for pushing the project forward.
 - [x] Make sure elements of the project are being properly tested.
 - [ ] #97
 - A skeleton of your report with two or three figure concepts. These may be graph ideas, plotting some of your data, overviews of your workflow, or some other conceptual figure. I just want you to think about what you are going to write, and how you want to showcase the work you've done.

**Comment by SoloSynth1** [comment]
@JohnShiuMK I'm thinking about putting content inside `src/gpt_4/` to elsewhere. Do you have any suggestions on this?

**Comment by SoloSynth1** [comment]
Closing this issue as the sub-issues are tracked by #99 instead.
